### Problem 1 : Add two randomly generated NumPy matrices using loops 
Exercise: Add two randomly generated NumPy 3D-matrices(tensor) using loops

In [4]:
import numpy as np
A1 = np.random.rand(3,3,3)
print(A1)

[[[0.03816047 0.10565558 0.21158239]
  [0.72045949 0.07034381 0.05727733]
  [0.24809731 0.81349548 0.84068659]]

 [[0.17430487 0.37772449 0.13869505]
  [0.48878483 0.77858192 0.64964487]
  [0.50394311 0.52245373 0.96826061]]

 [[0.71604037 0.6747494  0.68152737]
  [0.40273761 0.87468811 0.47745767]
  [0.01728933 0.37190164 0.75606011]]]


In [10]:
A2=np.random.rand(3,3,3)
print(A2)

[[[0.84117138 0.52178274 0.10229022]
  [0.14570154 0.13646954 0.6029956 ]
  [0.53850533 0.62957037 0.90673076]]

 [[0.02280706 0.18437768 0.76820884]
  [0.27804227 0.08966723 0.1750601 ]
  [0.04668165 0.90061943 0.85744274]]

 [[0.27873425 0.83471533 0.54863843]
  [0.09951885 0.51120455 0.10933566]
  [0.36540478 0.87598025 0.39391292]]]


In [11]:
(r,c,h) = A1.shape
print((r,c,h))

(3, 3, 3)


In [12]:
#Normal addition using 
B = A1 + A2
print(B)

[[[0.87933185 0.62743831 0.31387261]
  [0.86616103 0.20681335 0.66027292]
  [0.78660264 1.44306586 1.74741735]]

 [[0.19711193 0.56210217 0.90690389]
  [0.7668271  0.86824916 0.82470497]
  [0.55062477 1.42307316 1.82570335]]

 [[0.99477462 1.50946472 1.2301658 ]
  [0.50225645 1.38589266 0.58679332]
  [0.38269411 1.2478819  1.14997303]]]


In [19]:
#Adding two marices using loops
B = np.zeros((3,3,3)) #For Optimization , preallocate B
for i in range(r):
    for j in range(c):
        for k in range(h):
            B[i,j,k] = A1[i,j,k] + A2[i,j,k];
        
print(B)

[[[0.87933185 0.62743831 0.31387261]
  [0.86616103 0.20681335 0.66027292]
  [0.78660264 1.44306586 1.74741735]]

 [[0.19711193 0.56210217 0.90690389]
  [0.7668271  0.86824916 0.82470497]
  [0.55062477 1.42307316 1.82570335]]

 [[0.99477462 1.50946472 1.2301658 ]
  [0.50225645 1.38589266 0.58679332]
  [0.38269411 1.2478819  1.14997303]]]


<h3> Problem 2: Find if a given 2D point is inside (or) outside a rectangle ? </h3>

- Subproblems.

- Subproblems --> coding concepts.

- putting it all together.


Solution : The problem can be solved by taking diagonal points  and checking if the point is greater and lesser than those points

In [21]:
T1,T2 = map(float,input().split())

3.0 4.0


In [31]:
B1,B2 = map(float,input().split())


1.0 0.5


In [29]:
P1,P2 = map(float,input().split())

2.0 1.0


In [32]:
if(P1 < T1 and P1 > B1 and P2 < T2 and P2 > B2):
    print("Point is inside rectangle");
else:
    print("Point is outside rectangle");

Point is inside rectangle


<h3>Problem 3: Take a tensor of size 4x5x6 and convert it into tensor and matrix (10x12) </h3>

In [34]:
A = np.random.rand(4,5,6)

In [35]:
#Converting into 1D array using reshape
np.reshape(A,120,'C')

array([0.47219463, 0.77011813, 0.79780426, 0.96675746, 0.31985787,
       0.98457491, 0.8487412 , 0.62911815, 0.44782313, 0.26798052,
       0.52375972, 0.13529002, 0.05904575, 0.73755813, 0.43875874,
       0.75836904, 0.19829925, 0.8755676 , 0.02587522, 0.52316157,
       0.78509148, 0.47231776, 0.69695676, 0.12941745, 0.54617827,
       0.80076821, 0.97858447, 0.98888685, 0.07436757, 0.36220552,
       0.05989002, 0.73132552, 0.89152891, 0.00355648, 0.58652298,
       0.76406088, 0.93101985, 0.46969677, 0.21156349, 0.13525484,
       0.76347218, 0.97639066, 0.53430716, 0.31081428, 0.83709047,
       0.32084827, 0.08586223, 0.66546084, 0.10698437, 0.46045847,
       0.05129273, 0.47416142, 0.89106001, 0.23761767, 0.30636239,
       0.11740825, 0.38903349, 0.28824348, 0.32024416, 0.79854369,
       0.75674351, 0.45179543, 0.22707516, 0.19197558, 0.93782982,
       0.78011421, 0.90154048, 0.86906103, 0.35164439, 0.54249186,
       0.27055401, 0.07717209, 0.84150196, 0.06609039, 0.10194

In [36]:
#Converting it into 2D array of 10X12
np.reshape(A,(10,12),'C')

array([[0.47219463, 0.77011813, 0.79780426, 0.96675746, 0.31985787,
        0.98457491, 0.8487412 , 0.62911815, 0.44782313, 0.26798052,
        0.52375972, 0.13529002],
       [0.05904575, 0.73755813, 0.43875874, 0.75836904, 0.19829925,
        0.8755676 , 0.02587522, 0.52316157, 0.78509148, 0.47231776,
        0.69695676, 0.12941745],
       [0.54617827, 0.80076821, 0.97858447, 0.98888685, 0.07436757,
        0.36220552, 0.05989002, 0.73132552, 0.89152891, 0.00355648,
        0.58652298, 0.76406088],
       [0.93101985, 0.46969677, 0.21156349, 0.13525484, 0.76347218,
        0.97639066, 0.53430716, 0.31081428, 0.83709047, 0.32084827,
        0.08586223, 0.66546084],
       [0.10698437, 0.46045847, 0.05129273, 0.47416142, 0.89106001,
        0.23761767, 0.30636239, 0.11740825, 0.38903349, 0.28824348,
        0.32024416, 0.79854369],
       [0.75674351, 0.45179543, 0.22707516, 0.19197558, 0.93782982,
        0.78011421, 0.90154048, 0.86906103, 0.35164439, 0.54249186,
        0.27055401,

### Problem 4: Concatenating matrices using concatenate() function for both 2D and 3D

In [38]:
import numpy as np
A = np.random.rand(2,1)
print(A)

[[0.43622808]
 [0.8119    ]]


In [39]:
B = np.random.rand(2,2)
print(B)

[[0.0561156  0.4178601 ]
 [0.03030114 0.75121681]]


In [44]:
np.concatenate((A,B),axis=1) #This is similar to hstack where number of rows must be similar for 2D matrix

array([[0.43622808, 0.0561156 , 0.4178601 ],
       [0.8119    , 0.03030114, 0.75121681]])

In [45]:
A = np.random.rand(3,2)
print(A)

[[0.24260357 0.85479456]
 [0.54041599 0.30073888]
 [0.27145668 0.19611752]]


In [46]:
B = np.random.rand(2,1)
print(B)

[[0.37198899]
 [0.72813152]]


In [48]:
np.concatenate((A,B),axis=0) # This is similar to vstack where number of columns must be same for 2D matrix

ValueError: all the input array dimensions except for the concatenation axis must match exactly

In [49]:
A = np.random.rand(3,2)
print(A)

[[0.93796889 0.69302407]
 [0.76130647 0.86058143]
 [0.8600259  0.88997879]]


In [50]:
B = np.random.rand(2,2)
print(B)

[[0.07084682 0.8074299 ]
 [0.67135212 0.21418026]]


In [51]:
np.concatenate((A,B),axis=0) # This is similar to vstack where number of columns must be same for 2D matrix

array([[0.93796889, 0.69302407],
       [0.76130647, 0.86058143],
       [0.8600259 , 0.88997879],
       [0.07084682, 0.8074299 ],
       [0.67135212, 0.21418026]])

In [52]:
#For 3D matrix (h,w,d)
A = np.random.rand(3,2,3)
print(A)

[[[0.68268247 0.24629814 0.79225905]
  [0.7272486  0.59895671 0.60492927]]

 [[0.78180182 0.60459396 0.13598849]
  [0.26822237 0.92351169 0.64382495]]

 [[0.27315582 0.71741099 0.58210626]
  [0.48224219 0.08410569 0.90234056]]]


In [53]:
B = np.random.rand(3,4,3)
print(A)

[[[0.68268247 0.24629814 0.79225905]
  [0.7272486  0.59895671 0.60492927]]

 [[0.78180182 0.60459396 0.13598849]
  [0.26822237 0.92351169 0.64382495]]

 [[0.27315582 0.71741099 0.58210626]
  [0.48224219 0.08410569 0.90234056]]]


In [54]:
#This is similar to hstack here the height and depth must be same for both 3D matrices
np.concatenate((A,B),axis = 1) 


array([[[0.68268247, 0.24629814, 0.79225905],
        [0.7272486 , 0.59895671, 0.60492927],
        [0.8668409 , 0.38071195, 0.97257077],
        [0.34176256, 0.69064406, 0.1063275 ],
        [0.48141942, 0.68215095, 0.97578604],
        [0.83145175, 0.58163067, 0.09843516]],

       [[0.78180182, 0.60459396, 0.13598849],
        [0.26822237, 0.92351169, 0.64382495],
        [0.91903358, 0.39318429, 0.49796305],
        [0.63706948, 0.8370464 , 0.64034421],
        [0.34128924, 0.3674022 , 0.25047794],
        [0.82386873, 0.32642988, 0.61490544]],

       [[0.27315582, 0.71741099, 0.58210626],
        [0.48224219, 0.08410569, 0.90234056],
        [0.4750905 , 0.86861589, 0.9393686 ],
        [0.02963222, 0.01843054, 0.62667294],
        [0.67800848, 0.89064584, 0.08456083],
        [0.30334048, 0.50486082, 0.41288044]]])

In [55]:
A = np.random.rand(3,2,3)
print(A)

[[[0.01244696 0.55772029 0.73982675]
  [0.97255768 0.23076901 0.16237076]]

 [[0.6108433  0.57455752 0.84444958]
  [0.4495717  0.48970398 0.07152533]]

 [[0.70573645 0.57685409 0.50719093]
  [0.1078994  0.01819171 0.65830177]]]


In [56]:
B = np.random.rand(4,2,3)
print(B)

[[[0.29562232 0.51714465 0.075093  ]
  [0.99332271 0.77678343 0.14480375]]

 [[0.42932937 0.57987884 0.23316482]
  [0.71434551 0.32962104 0.61600406]]

 [[0.92269291 0.71003447 0.16287264]
  [0.10957546 0.24616313 0.33467137]]

 [[0.75073987 0.72727018 0.90617885]
  [0.62700417 0.80086708 0.66410709]]]


In [57]:
np.concatenate((A,B),axis = 0) #This is similar to vstack where the width and depth must be similar for 3D matrices

array([[[0.01244696, 0.55772029, 0.73982675],
        [0.97255768, 0.23076901, 0.16237076]],

       [[0.6108433 , 0.57455752, 0.84444958],
        [0.4495717 , 0.48970398, 0.07152533]],

       [[0.70573645, 0.57685409, 0.50719093],
        [0.1078994 , 0.01819171, 0.65830177]],

       [[0.29562232, 0.51714465, 0.075093  ],
        [0.99332271, 0.77678343, 0.14480375]],

       [[0.42932937, 0.57987884, 0.23316482],
        [0.71434551, 0.32962104, 0.61600406]],

       [[0.92269291, 0.71003447, 0.16287264],
        [0.10957546, 0.24616313, 0.33467137]],

       [[0.75073987, 0.72727018, 0.90617885],
        [0.62700417, 0.80086708, 0.66410709]]])

### Write a NumPy program to get the numpy version and show numpy build configuration.

In [63]:
import numpy as np
print(np.__version__) 
print(np.show_config())

1.16.2
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/VLakshmiSusmitha/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/VLakshmiSusmitha/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/VLakshmiSusmitha/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_librari

<h3>Write a NumPy program to  get help on the add function</h3>

In [66]:
import numpy as np
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

<h3>Write a NumPy program to test whether none of the elements of a given array is zero</h3>

In [67]:
import numpy as np
A = np.array([1,8,7,4,2,3])
print(A)
print(np.all(A)) #Return true if the array has all nonzero elements

[1 8 7 4 2 3]
True


In [74]:
B = np.array([0,8,7,4,2,3])
print(B)
print(np.all(B)) #Return false if the array has all nonzero elements

[0 8 7 4 2 3]
False


### Test a given array element-wise for finiteness (not infinity or not a Number)

In [76]:
import numpy as np
A = np.array([1,6,np.nan])
print(A)

[ 1.  6. nan]


In [79]:
print(np.isfinite(A))

[ True  True False]


In [78]:
B = np.array([1,6,np.nan,np.inf])
print(B)

[ 1.  6. nan inf]


In [80]:
print(np.isfinite(B))

[ True  True False False]


<h3>Write a NumPy program to test element-wise for positive or negative infinity</h3>

In [81]:
np.isinf([np.inf, -np.inf, 1.0, np.nan])

array([ True,  True, False, False])

<h3>Write a NumPy program to test element-wise for NaN of a given array.</h3>

In [83]:
np.isnan([np.nan,1,2])

array([ True, False, False])

<h3>Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.</h3>

In [89]:
np.iscomplex([1+1j, 1+0j, 4.5, 3, 2, 2j])

array([ True, False, False, False, False,  True])

In [90]:
np.isreal([1+1j, 1+0j, 4.5, 3, 2, 2j])

array([False,  True,  True,  True,  True, False])

In [91]:
np.isscalar('numpy')

True

<h3>Write a NumPy program to create an array of the integers from 30 to70</h3>

In [96]:
A = np.arange(30,71)
print(A)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


<h3> Write a NumPy program to create an array of all the even integers from 30 to 70</h3>

In [98]:
B = np.arange(30,71,2)
print(B)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


<h3>Write a NumPy program to create a 3x3 identity matrix</h3>

In [99]:
C =  np.identity(3)
print(C)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Python program to add two numbers

In [100]:
m,n = map(int,input().split())
print(m+n)

3 4
7


<h3>Reversal of String </h3>

In [4]:
B = ['r','o','m','e','i','n','e','u','m']

In [9]:
B[::-1]

['m', 'u', 'e', 'n', 'i', 'e', 'm', 'o', 'r']